# Generated by Django 3.2.9 on 2021-11-27 12:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('authors', django.db.models.manager.Manager()),
            ],
        ),
    ]
