# Generated by Django 3.2.9 on 2022-02-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20220223_2257'),
        ('blogsite', '0003_auto_20220223_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aricle_author', to='profiles.author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_author', to='profiles.author'),
        ),
    ]
