# Generated by Django 3.2.9 on 2022-04-22 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0006_auto_20220422_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sub_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogsite.subsector'),
        ),
    ]
