# Generated by Django 3.2.9 on 2022-04-24 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20220223_2257'),
        ('blogsite', '0007_alter_news_sub_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscomment',
            name='name',
        ),
        migrations.AddField(
            model_name='newscomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='profiles.author'),
        ),
    ]
