# Generated by Django 3.2.9 on 2022-04-24 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogsite', '0008_auto_20220424_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscomment',
            name='author',
        ),
        migrations.AddField(
            model_name='newscomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL),
        ),
    ]
